const refs = {
  searchForm: document.querySelector('.search-form'),
  gallery: document.querySelector('.gallery'),
  loadBtn: document.querySelector('.btn'),
  container: document.getElementById('js-container'),

  logo: document.getElementById('logo'),
  homeBtn: document.querySelector('.menu__link'),
  myLibraryBtn: document.getElementById('my-library'),
  header: document.querySelector('.header'),
  watchedBtn: document.querySelector('.watched-btn-js'),
  queuedBtn: document.querySelector('.queue-btn-js'),
  btnContainerLibrary: document.querySelector('.btn-container__library'),
  registrationForm: document.querySelector('.registration-form-js'),
  signInForm: document.querySelector('.signin-form-js'),
  signOutBtn: document.querySelector('.signout-btn-js'),
  backdrop: document.querySelector('.backdrop'),
  modalCloseBtn: document.querySelector('.team__modal-close-btn'),
  footerLink: document.getElementById('footer__link'),
  cardSectionLoader: document.getElementById('cardSectionLoader'),
  modalSignInClose: document.querySelector('[data-modal-auth-close]'),
  modalSignIn: document.querySelector('[data-modal-auth]'),
  modalRegistrationOpen: document.querySelector('[data-modal-registration-open]'),
  modalRegistrationClose: document.querySelector('[data-modal-registration-close]'),
  modalRegistration: document.querySelector('[data-modal-registration]'),
  goToRegistrationBtn: document.querySelector('.auth-form__registration-appeal'),


export const {
  searchForm,
  gallery,
  loadBtn,
  container,
  signInForm,
  logo,
  homeBtn,
  myLibraryBtn,
  header,
  watchedBtn,
  queuedBtn,
  btnContainerLibrary,
  signOutBtn,
  backdrop,
  modalCloseBtn,
  footerLink,
  cardSectionLoader,
  modalSignInOpen,
  modalSignInClose,
  modalSignIn,
  modalRegistrationOpen,
  modalRegistrationClose,
  modalRegistration,
  goToRegistrationBtn,
  registrationForm,
} = refs;
